provider:
  name: test
  params: { }

executor:
  params:
    driver: com.mysql.com.typeboot.executor.jdbc.Driver
    host: "127.0.0.1"
    port: "3306"
    username: root
    password: root
    database: executor
    table: cassandra_migrations
